#usr/bin/python3
"""
Module clui_lib.console.ibm_scancodes_mapping

Implements mapping of the 1-byte control codes and of the 2nd byte of 2-bytes
IBM scancodes sequence onto the actual keys or keys combinations.

Note that not definitions can be tested directly because them being intercepted
by OS or IDE, which prevents their capture by msvcrt handler.

Attributes:
    ASCII_CONTROL_MAPPING: dict(str -> list(str))
    IBM_SC_MAPPING: dict(int -> str)
"""

__version__= '1.0.0.0'
__date__ = '09-08-2021'
__status__ = 'Testing'

#globals

ASCII_CONTROL_MAPPING = {
    'SOH': ['Ctrl-a'],
    'STX': ['Ctrl-b'],
    'ETX': ['Ctrl-c'],
    'EOT': ['Ctrl-d'],
    'ENQ': ['Ctrl-e'],
    'ACK' : ['Ctrl-f'],
    'BEL' : ['Ctrl-g'],
    'BS' : ['Ctrl-h'],
    'TAB' : ['Tab', 'Ctrl-i'],
    'LF' : ['Enter', 'Ctrl-j'],
    'VT' : ['Ctrl-k'],
    'FF' : ['Ctrl-l'],
    'CR' : ['Enter', 'Ctrl-m'],
    'SO' : ['Ctrl-n'],
    'SI' : ['Ctrl-o'],
    'DLE' : ['Ctrl-p'],
    'DC1' : ['Ctrl-q'],
    'DC2' : ['Ctrl-r'],
    'DC3' : ['Ctrl-s'],
    'DC4' : ['Ctrl-t'],
    'NAK' : ['Ctrl-u'],
    'SYN' : ['Ctrl-v'],
    'ETB' : ['Ctrl-w'],
    'CAN' : ['Ctrl-x'],
    'EM' : ['Ctrl-y'],
    'SUB' : ['Ctrl-z'],
    'ESC' : ['Escape', 'Ctrl-['],
    'FS' : ['Ctrl-\\'],
    'GS' : ['Ctrl-]'],
    'SPACE' : ['Space'],
    'DEL' : ['Backspace']
}

IBM_SC_MAPPING = {
    2 : 'Ctrl-1',
    3 : 'Ctrl-2',
    4 : 'Ctrl-3',
    5 : 'Ctrl-4',
    6 : 'Ctrl-5',
    7 : 'Ctrl-6',
    8 : 'Ctrl-7',
    9 : 'Ctrl-8',
    10 : 'Ctrl-9',
    11 : 'Ctrl-0',
    16 : 'Ctrl-Alt-q',
    17 : 'Ctrl-Alt-w',
    18 : 'Ctrl-Alt-e',
    19 : 'Ctrl-Alt-r',
    20 : 'Ctrl-Alt-t',
    21 : 'Ctrl-Alt-y',
    22 : 'Ctrl-Alt-u',
    23 : 'Ctrl-Alt-i',
    24 : 'Ctrl-Alt-o',
    25 : 'Ctrl-Alt-p',
    26 : 'Ctrl-Alt-[',
    27 : 'Ctrl-Alt-]',
    28 : 'Ctrl-Alt-Enter',
    30 : 'Ctrl-Alt-a',
    31 : 'Ctrl-Alt-s',
    32 : 'Ctrl-Alt-d',
    33 : 'Ctrl-Alt-f',
    34 : 'Ctrl-Alt-g',
    35 : 'Ctrl-Alt-h',
    36 : 'Ctrl-Alt-j',
    37 : 'Ctrl-Alt-k',
    38 : 'Ctrl-Alt-l',
    39 : 'Ctrl-Alt-;',
    40 : 'Ctrl-Alt-\'',
    41 : 'Ctrl-Alt-`',
    44 : 'Ctrl-Alt-z',
    45 : 'Ctrl-Alt-x',
    46 : 'Ctrl-Alt-c',
    47 : 'Ctrl-Alt-v',
    48 : 'Ctrl-Alt-b',
    49 : 'Ctrl-Alt-n',
    50 : 'Ctrl-Alt-m',
    51 : 'Ctrl-Alt-,',
    52 : 'Ctrl-Alt-.',
    53 : 'Ctrl-Alt-/',
    59 : 'F1',
    60 : 'F2',
    61 : 'F3',
    62 : 'F4',
    63 : 'F5',
    64 : 'F6',
    65 : 'F7',
    66 : 'F8',
    67 : 'F9',
    68 : 'F10',
    71 : 'Home',
    72 : 'KeyUP',
    73 : 'PageUp',
    75 : 'KeyLEFT',
    77 : 'KeyRIGHT',
    79 : 'End',
    80 : 'KeyDOWN',
    81 : 'PageDown',
    82 : 'Insert',
    83 : 'Delete',
    84 : 'Shift-F1',
    85 : 'Shift-F2',
    86 : 'Shift-F3',
    87 : 'Shift-F4',
    88 : 'Shift-F5',
    89 : 'Shift-F6',
    90 : 'Shift-F7',
    91 : 'Shift-F8',
    92 : 'Shift-F9',
    93 : 'Shift-F10',
    94 : 'Ctrl-F1',
    95 : 'Ctrl-F2',
    96 : 'Ctrl-F3',
    97 : 'Ctrl-F4',
    98 : 'Ctrl-F5',
    99 : 'Ctrl-F6',
    100 : 'Ctrl-F7',
    101 : 'Ctrl-F8',
    102 : 'Ctrl-F9',
    103 : 'Ctrl-F10',
    104 : 'Alt-F1',
    105 : 'Alt-F2',
    106 : 'Alt-F3',
    107 : 'Alt-F4',
    108 : 'Alt-F5',
    109 : 'Alt-F6',
    110 : 'Alt-F7',
    111 : 'Alt-F8',
    112 : 'Alt-F9',
    113 : 'Alt-F10',
    115 : 'Ctrl-KeyLEFT',
    116 : 'Ctrl-KeyRIGHT',
    118 : 'Ctrl-PageUp',
    119 : 'Ctrl-Home',
    120 : 'Ctrl-Alt-1',
    121 : 'Ctrl-Alt-2',
    122 : 'Ctrl-Alt-3',
    123 : 'Ctrl-Alt-4',
    124 : 'Ctrl-Alt-5',
    125 : 'Ctrl-Alt-6',
    126 : 'Ctrl-Alt-7',
    127 : 'Ctrl-Alt-8',
    128 : 'Ctrl-Alt-9',
    129 : 'Ctrl-Alt-0',
    130 : 'Ctrl-Alt--',
    131 : 'Ctrl-Alt-=',
    133 : 'F11',
    134 : 'F12',
    135 : 'Shift-F11',
    136 : 'Shift-F12',
    137 : 'Ctrl-F11',
    138 : 'Ctrl-F12',
    139 : 'Alt-F11',
    140 : 'Alt-F12',
    141 : 'Ctrl-KeyUP',
    145 : 'Ctrl-KeyDOWN',
    146 : 'Ctrl-Insert',
    147 : 'Ctrl-Delete',
    149 : 'Ctrl-/',
    151 : 'Alt-Home',
    152 : 'Alt-KeyUP',
    153 : 'Alt-PageUp',
    155 : 'Alt-KeyLEFT',
    157 : 'Alt-KeyRIGHT',
    159 : 'Alt-End',
    160 : 'Alt-KeyDOWN',
    161 : 'Alt-PageDown',
    162 : 'Alt-Insert',
    163 : 'Alt-Delete',
    164 : 'Ctrl-Alt-/',
    166 : 'Ctrl-Alt-Enter'
}