#usr/bin/python3
"""
Module clui_lib.console.xterm_new_mapping

Implements mapping of the 1-byte control codes and CSI escape sequence codes
onto the actual keys or keys combinations according to the xterm documentation,
see https://invisible-island.net/xterm/xterm-function-keys.html.

Note that not definitions can be tested directly because them being intercepted
by OS or IDE, which prevents their appearance in the stdin.

Attributes:
    ASCII_CONTROL_MAPPING: dict(str -> list(str))
    CSI_MAPPING: dict(bytes -> str)
"""

__version__= '1.0.0.0'
__date__ = '06-08-2021'
__status__ = 'Testing'

#globals

ASCII_CONTROL_MAPPING = {
    'SOH': ['Ctrl-a'],
    'STX': ['Ctrl-b'],
    'ETX': ['Ctrl-c'],
    'EOT': ['Ctrl-d'],
    'ENQ': ['Ctrl-e'],
    'ACK' : ['Ctrl-f'],
    'BEL' : ['Ctrl-g'],
    'BS' : ['Ctrl-h'],
    'TAB' : ['Tab', 'Ctrl-i'],
    'LF' : ['Enter', 'Ctrl-j'],
    'VT' : ['Ctrl-k'],
    'FF' : ['Ctrl-l'],
    'CR' : ['Enter', 'Ctrl-m'],
    'SO' : ['Ctrl-n'],
    'SI' : ['Ctrl-o'],
    'DLE' : ['Ctrl-p'],
    'DC1' : ['Ctrl-q'],
    'DC2' : ['Ctrl-r'],
    'DC3' : ['Ctrl-s'],
    'DC4' : ['Ctrl-t'],
    'NAK' : ['Ctrl-u'],
    'SYN' : ['Ctrl-v'],
    'ETB' : ['Ctrl-w'],
    'CAN' : ['Ctrl-x'],
    'EM' : ['Ctrl-y'],
    'SUB' : ['Ctrl-z'],
    'ESC' : ['Escape', 'Ctrl-['],
    'FS' : ['Ctrl-\\'],
    'GS' : ['Ctrl-]'],
    'SPACE' : ['Space'],
    'DEL' : ['Backspace']
}


CSI_MAPPING = {
    b'\x1b[A' : 'KeyUP',
    b'\x1b[B' : 'KeyDOWN',
    b'\x1b[C' : 'KeyRIGHT',
    b'\x1b[D' : 'KeyLEFT',
    b'\x1b[F' : 'End',
    b'\x1b[H' : 'Home',
    b'\x1b[3~' : 'Delete',
    b'\x1b[5~' : 'PageUp',
    b'\x1b[6~' : 'PageDown',
    b'\x1b0P' : 'F1',
    b'\x1b0Q' : 'F2',
    b'\x1b0R' : 'F3',
    b'\x1b0S' : 'F4',
    b'\x1b[15~' : 'F5',
    b'\x1b[17~' : 'F6',
    b'\x1b[18~' : 'F7',
    b'\x1b[19~' : 'F8',
    b'\x1b[20~' : 'F9',
    b'\x1b[21~' : 'F10',
    b'\x1b[23~' : 'F11',
    b'\x1b[24~' : 'F12',
    b'\x1b[1;2A' : 'Shift-KeyUP',
    b'\x1b[1;2B' : 'Shift-KeyDOWN',
    b'\x1b[1;2C' : 'Shift-KeyRIGHT',
    b'\x1b[1;2D' : 'Shift-KeyLEFT',
    b'\x1b[1;2F' : 'Shift-End',
    b'\x1b[1;2H' : 'Shift-Home',
    b'\x1b[3;2~' : 'Shift-Delete',
    b'\x1b[5;2~' : 'Shift-PageUp',
    b'\x1b[6;2~' : 'Shift-PageDown',
    b'\x1b[1;2P' : 'Shift-F1',
    b'\x1b[1;2Q' : 'Shift-F2',
    b'\x1b[1;2R' : 'Shift-F3',
    b'\x1b[1;2S' : 'Shift-F4',
    b'\x1b[15;2~' : 'Shift-F5',
    b'\x1b[17;2~' : 'Shift-F6',
    b'\x1b[18;2~' : 'Shift-F7',
    b'\x1b[19;2~' : 'Shift-F8',
    b'\x1b[20;2~' : 'Shift-F9',
    b'\x1b[21;2~' : 'Shift-F10',
    b'\x1b[23;2~' : 'Shift-F11',
    b'\x1b[24;2~' : 'Shift-F12',
    b'\x1b[1;3A' : 'Alt-KeyUP',
    b'\x1b[1;3B' : 'Alt-KeyDOWN',
    b'\x1b[1;3C' : 'Alt-KeyRIGHT',
    b'\x1b[1;3D' : 'Alt-KeyLEFT',
    b'\x1b[1;3F' : 'Alt-End',
    b'\x1b[1;3H' : 'Alt-Home',
    b'\x1b[3;3~' : 'Alt-Delete',
    b'\x1b[5;3~' : 'Alt-PageUp',
    b'\x1b[6;3~' : 'Alt-PageDown',
    b'\x1b[1;3P' : 'Alt-F1',
    b'\x1b[1;3Q' : 'Alt-F2',
    b'\x1b[1;3R' : 'Alt-F3',
    b'\x1b[1;3S' : 'Alt-F4',
    b'\x1b[15;3~' : 'Alt-F5',
    b'\x1b[17;3~' : 'Alt-F6',
    b'\x1b[18;3~' : 'Alt-F7',
    b'\x1b[19;3~' : 'Alt-F8',
    b'\x1b[20;3~' : 'Alt-F9',
    b'\x1b[21;3~' : 'Alt-F10',
    b'\x1b[23;3~' : 'Alt-F11',
    b'\x1b[24;3~' : 'Alt-F12',
    b'\x1b[1;4A' : 'Alt-Shift-KeyUP',
    b'\x1b[1;4B' : 'Alt-Shift-KeyDOWN',
    b'\x1b[1;4C' : 'Alt-Shift-KeyRIGHT',
    b'\x1b[1;4D' : 'Alt-Shift-KeyLEFT',
    b'\x1b[1;4F' : 'Alt-Shift-End',
    b'\x1b[1;4H' : 'Alt-Shift-Home',
    b'\x1b[3;4~' : 'Alt-Shift-Delete',
    b'\x1b[5;4~' : 'Alt-Shift-PageUp',
    b'\x1b[6;4~' : 'Alt-Shift-PageDown',
    b'\x1b[1;4P' : 'Alt-Shift-F1',
    b'\x1b[1;4Q' : 'Alt-Shift-F2',
    b'\x1b[1;4R' : 'Alt-Shift-F3',
    b'\x1b[1;4S' : 'Alt-Shift-F4',
    b'\x1b[15;4~' : 'Alt-Shift-F5',
    b'\x1b[17;4~' : 'Alt-Shift-F6',
    b'\x1b[18;4~' : 'Alt-Shift-F7',
    b'\x1b[19;4~' : 'Alt-Shift-F8',
    b'\x1b[20;4~' : 'Alt-Shift-F9',
    b'\x1b[21;4~' : 'Alt-Shift-F10',
    b'\x1b[23;4~' : 'Alt-Shift-F11',
    b'\x1b[24;4~' : 'Alt-Shift-F12',
    b'\x1b[1;5A' : 'Ctrl-KeyUP',
    b'\x1b[1;5B' : 'Ctrl-KeyDOWN',
    b'\x1b[1;5C' : 'Ctrl-KeyRIGHT',
    b'\x1b[1;5D' : 'Ctrl-KeyLEFT',
    b'\x1b[1;5F' : 'Ctrl-End',
    b'\x1b[1;5H' : 'Ctrl-Home',
    b'\x1b[3;5~' : 'Ctrl-Delete',
    b'\x1b[5;5~' : 'Ctrl-PageUp',
    b'\x1b[6;5~' : 'Ctrl-PageDown',
    b'\x1b[1;5P' : 'Ctrl-F1',
    b'\x1b[1;5Q' : 'Ctrl-F2',
    b'\x1b[1;5R' : 'Ctrl-F3',
    b'\x1b[1;5S' : 'Ctrl-F4',
    b'\x1b[15;5~' : 'Ctrl-F5',
    b'\x1b[17;5~' : 'Ctrl-F6',
    b'\x1b[18;5~' : 'Ctrl-F7',
    b'\x1b[19;5~' : 'Ctrl-F8',
    b'\x1b[20;5~' : 'Ctrl-F9',
    b'\x1b[21;5~' : 'Ctrl-F10',
    b'\x1b[23;5~' : 'Ctrl-F11',
    b'\x1b[24;5~' : 'Ctrl-F12',
    b'\x1b[1;6A' : 'Ctrl-Shift-KeyUP',
    b'\x1b[1;6B' : 'Ctrl-Shift-KeyDOWN',
    b'\x1b[1;6C' : 'Ctrl-Shift-KeyRIGHT',
    b'\x1b[1;6D' : 'Ctrl-Shift-KeyLEFT',
    b'\x1b[1;6F' : 'Ctrl-Shift-End',
    b'\x1b[1;6H' : 'Ctrl-Shift-Home',
    b'\x1b[3;6~' : 'Ctrl-Shift-Delete',
    b'\x1b[5;6~' : 'Ctrl-Shift-PageUp',
    b'\x1b[6;6~' : 'Ctrl-Shift-PageDown',
    b'\x1b[1;6P' : 'Ctrl-Shift-F1',
    b'\x1b[1;6Q' : 'Ctrl-Shift-F2',
    b'\x1b[1;6R' : 'Ctrl-Shift-F3',
    b'\x1b[1;6S' : 'Ctrl-Shift-F4',
    b'\x1b[15;6~' : 'Ctrl-Shift-F5',
    b'\x1b[17;6~' : 'Ctrl-Shift-F6',
    b'\x1b[18;6~' : 'Ctrl-Shift-F7',
    b'\x1b[19;6~' : 'Ctrl-Shift-F8',
    b'\x1b[20;6~' : 'Ctrl-Shift-F9',
    b'\x1b[21;6~' : 'Ctrl-Shift-F10',
    b'\x1b[23;6~' : 'Ctrl-Shift-F11',
    b'\x1b[24;6~' : 'Ctrl-Shift-F12',
    b'\x1b[1;7A' : 'Ctrl-Alt-KeyUP',
    b'\x1b[1;7B' : 'Ctrl-Alt-KeyDOWN',
    b'\x1b[1;7C' : 'Ctrl-Alt-KeyRIGHT',
    b'\x1b[1;7D' : 'Ctrl-Alt-KeyLEFT',
    b'\x1b[1;7F' : 'Ctrl-Alt-End',
    b'\x1b[1;7H' : 'Ctrl-Alt-Home',
    b'\x1b[3;7~' : 'Ctrl-Alt-Delete',
    b'\x1b[5;7~' : 'Ctrl-Alt-PageUp',
    b'\x1b[6;7~' : 'Ctrl-Alt-PageDown',
    b'\x1b[1;7P' : 'Ctrl-Alt-F1',
    b'\x1b[1;7Q' : 'Ctrl-Alt-F2',
    b'\x1b[1;7R' : 'Ctrl-Alt-F3',
    b'\x1b[1;7S' : 'Ctrl-Alt-F4',
    b'\x1b[15;7~' : 'Ctrl-Alt-F5',
    b'\x1b[17;7~' : 'Ctrl-Alt-F6',
    b'\x1b[18;7~' : 'Ctrl-Alt-F7',
    b'\x1b[19;7~' : 'Ctrl-Alt-F8',
    b'\x1b[20;7~' : 'Ctrl-Alt-F9',
    b'\x1b[21;7~' : 'Ctrl-Alt-F10',
    b'\x1b[23;7~' : 'Ctrl-Alt-F11',
    b'\x1b[24;7~' : 'Ctrl-Alt-F12',
    b'\x1b\x01' : 'Ctrl-Alt-a',
    b'\x1b\x02' : 'Ctrl-Alt-b',
    b'\x1b\x03' : 'Ctrl-Alt-c',
    b'\x1b\x04' : 'Ctrl-Alt-d',
    b'\x1b\x05' : 'Ctrl-Alt-e',
    b'\x1b\x06' : 'Ctrl-Alt-f',
    b'\x1b\x07' : 'Ctrl-Alt-g',
    b'\x1b\x08' : 'Ctrl-Alt-h',
    b'\x1b\x09' : 'Ctrl-Alt-i',
    b'\x1b\x0a' : 'Ctrl-Alt-j',
    b'\x1b\x0b' : 'Ctrl-Alt-c',
    b'\x1b\x0c' : 'Ctrl-Alt-l',
    b'\x1b\x0d' : 'Ctrl-Alt-m',
    b'\x1b\x0e' : 'Ctrl-Alt-n',
    b'\x1b\x0f' : 'Ctrl-Alt-o',
    b'\x1b\x10' : 'Ctrl-Alt-p',
    b'\x1b\x11' : 'Ctrl-Alt-q',
    b'\x1b\x12' : 'Ctrl-Alt-r',
    b'\x1b\x13' : 'Ctrl-Alt-s',
    b'\x1b\x14' : 'Ctrl-Alt-t',
    b'\x1b\x15' : 'Ctrl-Alt-u',
    b'\x1b\x16' : 'Ctrl-Alt-v',
    b'\x1b\x17' : 'Ctrl-Alt-w',
    b'\x1b\x18' : 'Ctrl-Alt-x',
    b'\x1b\x19' : 'Ctrl-Alt-y',
    b'\x1b\x1a' : 'Ctrl-Alt-z',
    b'\x1b\x1b' : 'Ctrl-Alt-[',
    b'\x1b\x1c' : 'Ctrl-Alt-\\',
    b'\x1b\x1d' : 'Ctrl-Alt-]',
    b'\x1b\x1e' : 'Ctrl-Alt-^',
    b'\x1b\x1f' : 'Ctrl-Alt-_',
    b'\x1b\x7f' : 'Alt-Backspace'
}